eureka:
  client:
    service-url:
      defaultZone: http://springcloud-tools:8761/eureka/
server:
  port: 8900
spring:
  application:
    name: eureka-client
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 10.0.0.33
    port: 15672
    username: guest
    password: guest

