server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuifuan/springcloud-configuration.git
          search-paths: tools-config-repo
          default-label: master
          username: fuancui@gmail.com
          password:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: springcloud-tools
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://springcloud-tools:8761/eureka/
info:
  app:
    description: This is Spring Cloud remote Registration center.
    name: tools-config-server
    version: 0.0
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh