version: '2'
services:
  tools-auth:
    build:
      context: ./
      dockerfile: ./tools-auth/Dockerfile
    ports:
      - 8001:8001
    extra_hosts:
      - "tools-jdbc:172.17.0.1"
      - "tools-nacos:172.17.0.1"
    restart: always
    container_name: tools-auth
    hostname: tools-docker
    image: tools-auth
    environment:
      - JVM_OPTS=-Xmx256m -Xms512m -XX:MaxPermSize=128m
  tools-gateway:
    build:
      context: ./
      dockerfile: ./tools-gateway/Dockerfile
    ports:
      - 8443:8443
    restart: always
    container_name: tools-gateway
    hostname: tools-docker
    image: tools-gateway
    extra_hosts:
      - "tools-jdbc:172.17.0.1"
      - "tools-nacos:172.17.0.1"
    environment:
      - JVM_OPTS=-Xmx256m -Xms512m -XX:MaxPermSize=128m
  tools-service:
    build:
      context: ./
      dockerfile: ./tools-service/Dockerfile
    ports:
      - 8848:8848
    restart: always
    container_name: tools-service
    hostname: tools-docker
    image: tools-service
    extra_hosts:
      - "tools-jdbc:172.17.0.1"
      - "tools-nacos:172.17.0.1"
    environment:
      - JVM_OPTS=-Xmx256m -Xms512m -XX:MaxPermSize=128m