version: '3'

services:
  mysql5.7:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # 设置root用户密码
    ports:
      - 3306:3306
    volumes: # 挂载持久化地址（个人理解）
      - ./docker/mysql/:/var/lib/mysql/
      - ./docker/conf/:/etc/mysql/
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./docker/nacos/standalone-logs/:/home/nacos/logs
      - ./docker/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker/nacos/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
# 暂时用不到redis
#  redis:
#    image: redis:4.0.2
#    container_name: my_redis
#    volumes:
#      - ./docker/redis/data:/data
#      - ./docker/redis/conf/:/usr/local/etc/redis/
#    command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
#    ports:
#      - 8089:6379