#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: tools-auth
#          predicates:
#            - Path=/auth/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=1
#          uri: lb://tools-auth
#        - id: tools-service
#          predicates:
#            - Path=/service/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=1
#          uri: lb://tools-service