spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: tools-auth
          uri: lb://tools-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            #            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #UPMS 模块
        - id: tools-admin
          uri: lb://tools-admin
          predicates:
            - Path=/admin/**
          filters:
            # 限流配置(filter名称必须是RequestRateLimiter)
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                # redis-rate-limiter.replenishRate：允许用户每秒处理多少个请求
                redis-rate-limiter.replenishRate: 10
                # redis-rate-limiter.burstCapacity：令牌桶的容量，允许在一秒钟内完成的最大请求数
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # 代码生成模块
        - id: tools-codegen
          uri: lb://tools-codegen
          predicates:
            - Path=/gen/**


security:
  encode:
    # 前端密码密钥，必须16位
    key: '1234567812345678'

# 不校验验证码终端
ignore:
  clients:
    - test
