## spring security 配置
security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin
      scope: server

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(eYFwbGW3Txj0rVSxsIrN8Q==)
    password: ENC(HrWgNhNbfnGfNYEU2jHnqw==)
    url: jdbc:mysql://tools-mysql:3306/tools?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  resources:
    static-locations: classpath:/static/,classpath:/views/

# 直接放行URL
ignore:
  urls:
    - /actuator/**
