server:
  port: 7003
spring:
  application:
    name: tools-config-client
  cloud:
    config:
  #配置重试机制
      retry:
        initial-interval: 2000
        max-attempts: 2000
        max-interval: 2000
        multiplier: 1.2
      fail-fast: true
    bus:
      #动态刷新配置
      refresh:
        enabled: true
      #跟踪总线事件
      trace:
        enabled: true
  rabbitmq:
    host: springcloud-tools
    port: 5672
    username: admin
    password: 123456
#配置actuator
# 1.X版本的springboot 配置： management.security.enabled=false  已经作废
#关闭安全认证
management:
  endpoint:
    bus-refresh:
      enabled: true
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh