server:
  port: 8761
spring:
  application:
    name: tools-eureka
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    hostname: tools-eureka
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    # 意味着自身仅作为服务器，不作为客户端
    register-with-eureka: false
    # 无需注册自身
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@tools-eureka:8761/eureka/
  # 更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置
  server:
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 5000
    # 设为false，关闭自我保护
    enable-self-preservation: false
    # 触发自我保护的心跳数比例阈值
    renewal-percent-threshold: 0.9
#  * can be used to select all endpoints,yml(so be sure to add quotes)
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'